[runbook]
title       = "daily"
description = "Runbook for daily"
version     = "0.1.0"
author      = "tw"
created_at  = "2025-05-04T15:21:46.173786+00:00"

[anki]
type         = "Command"
command_name = "open /Applications/Anki.app --args -b $HOME/dev/s/private/other-anki/data"
description  = "Learn"
depends_on   = []
prompt_after = "Are you done?"  # skipt prompting
skip         = false

[edit-daily]
type         = "Command"
command_name = "SPRING_DATASOURCE_URL=jdbc:sqlite:/Users/Q187392/dev/s/private/vimwiki/diary/daily_cli.db cli daily today"
description  = "Edit the file"
depends_on   = []
prompt_after = "Continue?"  # skipt prompting
skip         = false
interactive  = true

[login]
type         = "Manual"
prompt_after = "Are you logged in?"
description   = """Login required for subsequent steps"""
depends_on  = []
critical    = true

[open-itsm]
type         = "Command"
command_name = """open https://bmwgroupprod.service-now.com/now/nav/ui/classic/params/target/incident_list.do%3Fsysparm_query%3Dassignment_group%253D9b81facd1b9ff55099e7c9543b4bcb6b%255EGROUPBYpriority%26sysparm_first_row%3D1%26sysparm_view%3D"""
description  = "open ITSM"
depends_on   = ["login"]
prompt_after = "Have you checked the tickets?"
skip         = false

[git-los-prs]
type         = "Command"
command_name = """open https://atc-github.azure.cloud.bmw/pulls"""
description  = "open LOS PRs"
depends_on   = ["login"]
prompt_after = "Have you checked the LOS PRs?"
skip         = false

[git-los-outlook]
type         = "Manual"
description  = "Check the LOS folder in Outlook"
depends_on   = ["login"]
prompt_after = "Have you checked the LOS Folder in Outlook?"
skip         = false

# Example function node - uncomment to use
# [notify]
# type           = "Function"
# function_name  = "playbook.functions.notify"
# function_params = { "message" = "Deployment complete" }
# description    = "Sends deployment completion notification"
# depends_on     = []
