[runbook]
title       = "xxx"
description = "Runbook for xxx"
version     = "0.1.0"
author      = "tw"
created_at  = "2025-05-03T12:24:10.851769+00:00"

# Example manual node - uncomment to use
[approve]
type        = "Manual"
prompt      = "Proceed with deployment?"
depends_on  = []
skippable   = false
critical    = true

# Example command node - uncomment to use
[build]
type         = "Command"
command_name = "echo 'Hello, World!'"
depends_on   = []
timeout      = 300
name         = "Build step"

# Example function node - uncomment to use
[notify]
type           = "Function"
function_name  = "playbook.functions.notify"
function_params = { "message" = "Deployment complete" }
depends_on     = []
