[runbook]
title       = "complex"
description = "Runbook for complex"
version     = "0.1.0"
author      = "tw"
created_at  = "2025-05-03T12:24:10.851769+00:00"

[start]
type         = "Manual"
prompt      = "Proceed with deployment?"
description  = "Start of the workflow"
depends_on   = []

[a]
type        = "Manual"
prompt      = "Proceed with deployment?"
description  = "Branch A"
depends_on   = ["start", "d"]

[b]
type         = "Command"
command_name = "echo Task B"
description  = "Branch B"
depends_on   = ["start"]

[c]
type         = "Function"
function_name  = "playbook.functions.notify"
function_params = { "message" = "Deployment complete" }
description  = "Runs after A"
depends_on   = ["a"]

[d]
type         = "Command"
command_name = "echo Task D"
description  = "Runs after B"
depends_on   = ["b"]

[e]
type         = "Manual"
prompt      = "Proceed with deployment?"
description  = "Parallel task after A and B"
depends_on   = ["a", "b"]

[f]
type         = "Manual"
prompt      = "Proceed with deployment?"
description  = "Merges C and D"
depends_on   = ["c", "d"]

[g]
type         = "Function"
function_name  = "playbook.functions.notify"
function_params = { "message" = "Deployment complete" }
description  = "Runs after E"
depends_on   = ["e"]

[h]
type         = "Function"
function_name  = "playbook.functions.notify"
function_params = { "message" = "Deployment complete" }
description  = "Merges F and G"
depends_on   = ["f", "g"]

[end]
type         = "Manual"
prompt      = "Proceed with deployment?"
description  = "Final node"
depends_on   = ["h"]
