# Conditional Dependencies Syntax Example
# This example demonstrates the shorthand conditional dependency syntax

[runbook]
title = "Conditional Dependencies Example"
description = """
Demonstrates conditional dependency syntax using shorthand notation (node_id:success/failure).
This example shows how to create branching workflows that respond to node outcomes,
including success paths, failure handling, and cleanup operations.
"""
version = "1.0.0"
author = "devops-team"
created_at = "2025-01-20T12:00:00Z"

# Build step (always runs first)
[build]
type = "Command"
command_name = "make build"
description = """
Build the application from source code with all dependencies.
This foundational step compiles, packages, and prepares the application
for testing and deployment, ensuring all build requirements are satisfied.
"""
depends_on = []

# Test step (depends on build completing)
[test]
type = "Command"
command_name = "make test"
description = """
Execute comprehensive test suite including unit and integration tests.
Validates application functionality, performance, and quality standards
before proceeding with deployment to any environment.
"""
depends_on = ["build"]

# Deploy step (only runs if tests succeed)
[deploy]
type = "Command"
command_name = "make deploy"
description = """
Deploy the tested application to the target environment.
This step handles service deployment, configuration updates, and
ensures the application is properly running and accessible.
"""
depends_on = ["test:success"]  # Shorthand for: when = "{{ has_succeeded('test') }}"

# Rollback step (only runs if deploy fails)
[rollback]
type = "Command"
command_name = "make rollback"
description = """
Rollback the deployment to the previous stable version.
Activated only when deployment fails, this step restores service
to the last known good state and minimizes downtime impact.
"""
depends_on = ["deploy:failure"]  # Shorthand for: when = "{{ has_failed('deploy') }}"

# Cleanup success (runs if deploy succeeds)
[cleanup_success]
type = "Command"
command_name = "cleanup.sh --mode=success"
description = """
Perform cleanup operations following successful deployment.
Removes temporary files, old artifacts, and optimizes the environment
for ongoing operations while preserving necessary logs and backups.
"""
depends_on = ["deploy:success"]

# Cleanup failure (runs if deploy fails OR rollback succeeds)
[cleanup_failure]
type = "Command"
command_name = "cleanup.sh --mode=failure"
description = """
Perform cleanup operations following deployment failure or rollback.
Handles error artifacts, diagnostic data collection, and environment
stabilization to prepare for future deployment attempts.
"""
depends_on = ["deploy:failure", "rollback:success"]  # Multiple conditions with AND

# Notification (runs after any cleanup)
[notify]
type = "Manual"
prompt_after = "Deployment process completed. Review logs and continue."
description = """
Provide final notification about deployment process completion.
Summarizes the workflow outcome, provides status information,
and enables review of logs and results before concluding the process.
"""
depends_on = ["cleanup_success", "cleanup_failure"]
# This will run if either cleanup_success OR cleanup_failure completes
# (regular dependencies are OR by default, conditions within depends_on are AND)