[runbook]
title = "Python Plugin Demo (Fully Automated)"
description = "Automated demo of Python plugin functionality"
version = "1.0.0"
author = "Playbook Team"
created_at = "2025-01-20T12:00:00Z"

[variables]
APP_NAME = { default = "demo-app", description = "Application name for demo" }

[start_notification]
type = "Function"
plugin = "python"
function = "notify"
function_params = { message = "🚀 Starting automated Python plugin demo for {{APP_NAME}}" }
description = "Send startup notification"
depends_on = []

[demonstrate_sleep]
type = "Function"
plugin = "python"
function = "sleep"
function_params = { seconds = 1 }
description = "Demonstrate Python sleep function (1 second)"
depends_on = ["start_notification"]


[completion_notification]
type = "Function"
plugin = "python"
function = "notify"
function_params = { message = "✅ All Python plugin utility functions (notify, sleep, throw) demonstrated successfully!" }
description = "Send completion notification"
depends_on = ["demonstrate_sleep"]